Spo 6497 create term of user cell
surfstudio/ios-practice-malygin pull request #13
Opened 2021-07-13 10:18 UTC by gmngg

# Что сделано

- Ячейка пользовательского соглашения
- Начальная конфигурация экрана Feedback 

# На что обратить внимание
- Сделано кастомное нажатие на часть лейбла

# Как проверить

- Профиль>Обратная связь

# Чеклист

Общее:
- [ ] Я запустил проект перед тем как создать PR

Верстка:
- [ ] Я проверил верстку на SE, 7 и X 
- [ ] Я проверил верстку на iOS 12, 13, 14

Логика:
- [ ] Я проверил, что сетевой слой работает правильно

2021-07-14 07:35 UTC, chausovSurfStudio requested changes

2021-07-14 07:35 UTC, chausovSurfStudio commented on Flows/FeedbackFlow/Feedback/Feedback/Presenter/FeedbackPresenter.swift
> +    }
реализацию методов лучше определять в том же порядке, в котором они объявлены в протоколе - проще ориентироваться, когда их больше становится, а так как у нас обычно close-события в конце идут - в протоколе ViewOutput объявлено все верно, а вот тут вот showTermOfUser и closeModule лучше местами поменять)

2021-07-14 07:35 UTC, chausovSurfStudio commented on Flows/FeedbackFlow/Feedback/Feedback/View/Adapter/Cell/FeedbackAgreementCell.swift
> +class FeedbackAgreementCell: UITableViewCell {
final дописать

2021-07-14 07:35 UTC, chausovSurfStudio commented on Flows/FeedbackFlow/Feedback/Feedback/View/Adapter/Cell/FeedbackAgreementCell.swift
> +            complication()
а может просто здесь `termsDidTap?()` вызвать? у нас как-то вложенные методы не в почете)

2021-07-14 07:35 UTC, chausovSurfStudio commented on Flows/FeedbackFlow/Feedback/Feedback/View/Adapter/Cell/FeedbackAgreementCell.swift
> +        activeLabel.text = model.termOfUse
а, да, наверное не рассказывал
ограничения есть для стилей - сначала вставляем текст, а потом применяем стиль (под капотом берется текущий текст, из него генерится attributedString и устанавливается в лейбл. Если в другом порядке - то стиль может быть потерян, так как его затрет вот этот текст)
ибо вот на 12ой оси не применились они
![Снимок экрана 2021-07-14 в 10 28 16](https://user-images.githubusercontent.com/8776643/125581054-39ee84b4-be73-4f61-8216-d458047e77a8.png)

2021-07-14 07:35 UTC, chausovSurfStudio commented on Flows/FeedbackFlow/Feedback/Feedback/View/Adapter/Cell/FeedbackAgreementModel.swift
> +public struct FeedbackAgreementModel {
а наверное и нет смысла здесь в public, раз сама ячейка, куда моделька относится, internal-уровня

2021-07-14 07:35 UTC, chausovSurfStudio commented on Flows/FeedbackFlow/Feedback/Feedback/View/Adapter/FeedbackAdapter.swift
> +    init(tableView: UITableView) {
марк заодно добавь, раз уж править будешь)

2021-07-14 07:35 UTC, chausovSurfStudio commented on Flows/FeedbackFlow/Feedback/Feedback/View/Adapter/FeedbackAdapter.swift
> +    func file() {
кажется, это `fill` если ты имел в виду в качестве названия метода что-то типа "заполнить")

2021-07-14 07:35 UTC, chausovSurfStudio commented on Flows/FeedbackFlow/Feedback/Feedback/View/FeedbackViewController.swift
> +        fill()
вот этого здесь не должно по идее быть... но в целом это к следующей задаче, так что можешь там править, если осталось еще
смысл какой: экран появляется, таблица заполняется - и по идее она должна заполнится без какого-либо вмешательства извне. А тут торчит метод, который надо обязательно вызвать, а если не вызвать - то будет пустая таблица... лучше этот метод под капотом в адаптере вызывать, в его init методе

2021-07-14 10:54 UTC, chausovSurfStudio approved these changes

2021-07-14 10:56 UTC, tranina-olesya approved these changes

2021-07-14 10:56 UTC, tranina-olesya commented on Flows/FeedbackFlow/Feedback/Feedback/View/Adapter/Cell/FeedbackAgreementGenerator.swift
> +    private var cell: FeedbackAgreementCell?
а зачем тут ячейка? вроде не используется, можно не сохранять в генераторе
а хотя может дальше пригодится)

2021-07-15 05:18 UTC, tranina-olesya commented on Flows/FeedbackFlow/Feedback/Feedback/View/Adapter/Cell/FeedbackAgreementCell.swift
> +            switch sender.state {
только выравнивание нужно поправить, слишком вправо уплыло

2021-07-15 05:18 UTC, tranina-olesya commented on Flows/FeedbackFlow/Feedback/Feedback/View/Adapter/Cell/FeedbackAgreementGenerator.swift
> +                                                     termOfUse: L10n.Feedback.Feedback.Terms.termOfUse))
и здесь

2021-07-15 12:39 UTC, merged